// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Planilharias.Infrastructure.Data;

#nullable disable

namespace Planilharias.Infrastructure.Migrations
{
    [DbContext(typeof(PlanilhariasDbContext))]
    [Migration("20260610003649_CriaTabelasIniciais")]
    partial class CriaTabelasIniciais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Planilharias.Domain.Sheets.Sheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Dictionary<string, string>>("Cells")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("cells");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("WorkbookId")
                        .HasColumnType("uuid")
                        .HasColumnName("workbook_id");

                    b.HasKey("Id")
                        .HasName("pk_sheets");

                    b.HasIndex("WorkbookId")
                        .HasDatabaseName("ix_sheets_workbook_id");

                    b.ToTable("sheets", (string)null);
                });

            modelBuilder.Entity("Planilharias.Domain.Workbooks.Workbook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_workbooks");

                    b.ToTable("workbooks", (string)null);
                });

            modelBuilder.Entity("Planilharias.Domain.Sheets.Sheet", b =>
                {
                    b.HasOne("Planilharias.Domain.Workbooks.Workbook", "Workbook")
                        .WithMany("Sheets")
                        .HasForeignKey("WorkbookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sheets_workbooks_workbook_id");

                    b.Navigation("Workbook");
                });

            modelBuilder.Entity("Planilharias.Domain.Workbooks.Workbook", b =>
                {
                    b.Navigation("Sheets");
                });
#pragma warning restore 612, 618
        }
    }
}
